from __future__ import annotations

# Azure Language / Presidio-aligned enterprise taxonomy.
# Contextual types go to GLiNER. Strict identifiers stay regex/dictionary.

LABEL_ALIASES = {
    "COMPANY": "ORGANIZATION",
    "ORGANISATION": "ORGANIZATION",
    "CORPORATION": "ORGANIZATION",
    "FIRM": "ORGANIZATION",
    "BUSINESS": "ORGANIZATION",
    "ENTERPRISE": "ORGANIZATION",
    "ORG": "ORGANIZATION",
    "GPE": "LOCATION",
    "GEO": "LOCATION",
    "PLACE": "LOCATION",
    "LOC": "LOCATION",
    "PERSON_NAME": "PERSON",
    "PER": "PERSON",
    "PEOPLE": "PERSON",
    "JOB_TITLE": "DESIGNATION",
    "JOB TITLE": "DESIGNATION",
    "TITLE": "DESIGNATION",
    "ROLE": "DESIGNATION",
    "PHONE NUMBER": "PHONE",
    "PHONE_NUMBER": "PHONE",
    "MOBILE": "PHONE",
    "MOBILE_NUMBER": "PHONE",
    "TEL": "PHONE",
    "EMAIL ADDRESS": "EMAIL",
    "EMAIL_ADDRESS": "EMAIL",
    "MAIL": "EMAIL",
    "URL": "WEBSITE",
    "URI": "WEBSITE",
    "LINK": "WEBSITE",
    "DATETIME": "DATE",
    "DATE_TIME": "DATE",
    "ZIPCODE": "ZIP_CODE",
    "ZIP": "ZIP_CODE",
    "POSTCODE": "ZIP_CODE",
    "PINCODE": "ZIP_CODE",
    "PIN_CODE": "ZIP_CODE",
    "POSTAL_CODE": "ZIP_CODE",
    "HOSPITAL NAME": "HOSPITAL",
    "DOCTOR NAME": "DOCTOR",
    "PHYSICIAN": "DOCTOR",
    "MEDICAL PROCEDURE": "MEDICAL_PROCEDURE",
    "PROCEDURE": "MEDICAL_PROCEDURE",
    "MEDICINE NAME": "MEDICINE",
    "DRUG": "MEDICINE",
    "PROGRAMMING LANGUAGE": "PROGRAMMING_LANGUAGE",
    "MODEL NAME": "MODEL_NAME",
    "AI_MODEL": "MODEL_NAME",
    "GAME NAME": "GAME_NAME",
    "FILE NAME": "FILE_NAME",
    "DOCUMENT TYPE": "DOCUMENT_TYPE",
    "DOCUMENT NUMBER": "DOCUMENT_NUMBER",
    "DOCUMENT TITLE": "DOCUMENT_TITLE",
    "BANK ACCOUNT": "BANK_ACCOUNT",
    "ACCOUNT NUMBER": "BANK_ACCOUNT",
    "ACCOUNT_NO": "BANK_ACCOUNT",
    "IFSC CODE": "IFSC",
    "GST NUMBER": "GST",
    "GSTIN": "GST",
    "PAN NUMBER": "PAN",
    "AADHAR NUMBER": "AADHAR",
    "AADHAAR": "AADHAR",
    "PASSPORT NUMBER": "PASSPORT",
    "SSN": "US_SSN",
    "SOCIAL_SECURITY": "US_SSN",
    "SOCIAL SECURITY NUMBER": "US_SSN",
    "IBAN": "IBAN",
    "SWIFT": "SWIFT_CODE",
    "BIC": "SWIFT_CODE",
    "DRIVERS_LICENSE": "DRIVERS_LICENSE",
    "DRIVER_LICENSE": "DRIVERS_LICENSE",
    "DRIVING_LICENSE": "DRIVERS_LICENSE",
    "THREAT ACTOR": "THREAT_ACTOR",
    "SECURITY THREAT": "SECURITY_THREAT",
    "MILITARY UNIT": "MILITARY_UNIT",
    "IP": "IP_ADDRESS",
    "IPV4": "IP_ADDRESS",
    "IPV6": "IP_ADDRESS_V6",
    "MAC": "MAC_ADDRESS",
    "HASH VALUE": "HASH",
    "IOC": "IOC",
    "AMOUNT": "MONEY",
    "CURRENCY": "MONEY",
    "NUMBER": "QUANTITY",
    "QTY": "QUANTITY",
}

MODEL_LABEL_PROMPTS = {
    "PERSON": "person",
    "ORGANIZATION": "organization",
    "LOCATION": "location",
    "CITY": "city",
    "STATE": "state",
    "COUNTRY": "country",
    "ADDRESS": "address",
    "ZIP_CODE": "zip code",
    "DATE": "date",
    "TIME": "time",
    "QUANTITY": "quantity",
    "EMAIL": "email address",
    "PHONE": "phone number",
    "WEBSITE": "website",
    "DESIGNATION": "job title",
    "DEPARTMENT": "department",
    "PROJECT": "project",
    "PRODUCT": "product",
    "SKILL": "skill",
    "CUSTOMER": "customer",
    "SUPPLIER": "supplier",
    "MONEY": "money",
    "PERCENTAGE": "percentage",
    "NATIONALITY": "nationality",
    "TECHNOLOGY": "technology",
    "PROGRAMMING_LANGUAGE": "programming language",
    "MODEL_NAME": "ai model",
    "TEAM": "sports team",
    "COMPETITION": "competition",
    "GAME_NAME": "game",
    "MOVIE": "movie",
    "BOOK": "book",
    "TV_SERIES": "television series",
    "AUTHOR": "author",
    "ACTOR": "actor",
    "DOCTOR": "doctor",
    "HOSPITAL": "hospital",
    "MEDICINE": "medicine",
    "DISEASE": "disease",
    "SYMPTOM": "medical symptom",
    "MEDICAL_PROCEDURE": "medical procedure",
    "DOCUMENT_TYPE": "document type",
    "DOCUMENT_TITLE": "document title",
    "DOCUMENT_NUMBER": "document number",
    "BANK": "bank",
    "BANK_ACCOUNT": "bank account",
    "IFSC": "ifsc code",
    "GST": "gst number",
    "PAN": "pan number",
    "AADHAR": "aadhar number",
    "PASSPORT": "passport",
    "CREDIT_CARD": "credit card",
    "US_SSN": "social security number",
    "IBAN": "iban",
    "SWIFT_CODE": "swift code",
    "DRIVERS_LICENSE": "driver license",
    "VIN": "vehicle identification number",
    "UUID": "uuid",
    "IP_ADDRESS": "ip address",
    "IP_ADDRESS_V6": "ipv6 address",
    "MAC_ADDRESS": "mac address",
    "HASH": "file hash",
    "IOC": "indicator of compromise",
    "MALWARE": "malware",
    "RANSOMWARE": "ransomware",
    "CVE": "cve identifier",
    "CWE": "cwe identifier",
    "SECURITY_THREAT": "security threat",
    "THREAT_ACTOR": "threat actor",
    "MILITARY_UNIT": "military unit",
    "WEAPON": "weapon",
    "INFRASTRUCTURE": "critical infrastructure",
    "AGREEMENT": "agreement",
    "EVENT": "event",
    "AWARD": "award",
}

PROMPT_TO_LABEL = {
    prompt.lower(): label for label, prompt in MODEL_LABEL_PROMPTS.items()
}

STRUCTURED_LABELS = {
    "DOCUMENT_TITLE",
    "DOCUMENT_NUMBER",
    "DOCUMENT_TYPE",
    "REFERENCE_ID",
    "FILE_NAME",
    "CLASSIFICATION",
    "KEYWORD",
    "STATUS",
    "ORIGIN",
    "DESTINATION",
    "ITEM",
}

REGEX_ONLY_LABELS = {
    "EMAIL",
    "PHONE",
    "WEBSITE",
    "CREDIT_CARD",
    "AADHAR",
    "PAN",
    "GST",
    "PASSPORT",
    "BANK_ACCOUNT",
    "IFSC",
    "ZIP_CODE",
    "IP_ADDRESS",
    "IP_ADDRESS_V6",
    "MAC_ADDRESS",
    "HASH",
    "US_SSN",
    "IBAN",
    "SWIFT_CODE",
    "DRIVERS_LICENSE",
    "VIN",
    "UUID",
    "CVE",
    "CWE",
    "PERCENTAGE",
    "MONEY",
}

DICTIONARY_ONLY_LABELS = {
    "CITY",
    "STATE",
    "COUNTRY",
    "MEDICINE",
    "DISEASE",
    "DOCUMENT_TYPE",
    "MALWARE",
    "RANSOMWARE",
    "SECURITY_THREAT",
    "IOC",
}

# Contextual types the fine-tuned GLiNER model must learn.
PRODUCTION_TRAINING_LABELS = [
    "PERSON",
    "ORGANIZATION",
    "LOCATION",
    "ADDRESS",
    "DATE",
    "TIME",
    "EVENT",
    "PRODUCT",
    "SKILL",
    "DESIGNATION",
    "DEPARTMENT",
    "PROJECT",
    "QUANTITY",
    "NATIONALITY",
    "TECHNOLOGY",
    "PROGRAMMING_LANGUAGE",
    "MODEL_NAME",
    "TEAM",
    "COMPETITION",
    "DOCTOR",
    "HOSPITAL",
    "MEDICINE",
    "DISEASE",
    "BANK",
    "WEAPON",
    "THREAT_ACTOR",
    "MILITARY_UNIT",
    "INFRASTRUCTURE",
    "AGREEMENT",
    "AWARD",
]

CORE_ALWAYS_ON_LABELS = [
    "PERSON",
    "ORGANIZATION",
    "LOCATION",
    "DATE",
    "ADDRESS",
    "EVENT",
    "PRODUCT",
    "DESIGNATION",
    "QUANTITY",
]

ENTITY_PROFILES = {
    "general": [
        "PERSON",
        "ORGANIZATION",
        "LOCATION",
        "DATE",
        "TIME",
        "ADDRESS",
        "EVENT",
        "PRODUCT",
        "SKILL",
        "QUANTITY",
        "NATIONALITY",
        "EMAIL",
        "PHONE",
    ],
    "business": [
        "PERSON",
        "ORGANIZATION",
        "DESIGNATION",
        "DEPARTMENT",
        "PROJECT",
        "PRODUCT",
        "CUSTOMER",
        "SUPPLIER",
        "MONEY",
        "PERCENTAGE",
        "AGREEMENT",
        "BANK",
    ],
    "technology": [
        "PERSON",
        "ORGANIZATION",
        "TECHNOLOGY",
        "PROGRAMMING_LANGUAGE",
        "MODEL_NAME",
        "PROJECT",
        "PRODUCT",
        "SKILL",
    ],
    "medical": [
        "PERSON",
        "DOCTOR",
        "HOSPITAL",
        "MEDICINE",
        "DISEASE",
        "SYMPTOM",
        "MEDICAL_PROCEDURE",
        "DATE",
    ],
    "sports": [
        "PERSON",
        "TEAM",
        "COMPETITION",
        "GAME_NAME",
        "EVENT",
        "AWARD",
    ],
    "media": [
        "PERSON",
        "MOVIE",
        "BOOK",
        "TV_SERIES",
        "AUTHOR",
        "ACTOR",
    ],
    "finance": [
        "BANK",
        "BANK_ACCOUNT",
        "IFSC",
        "PAN",
        "AADHAR",
        "PASSPORT",
        "GST",
        "MONEY",
        "US_SSN",
        "IBAN",
        "SWIFT_CODE",
        "CREDIT_CARD",
    ],
    "security": [
        "PERSON",
        "ORGANIZATION",
        "WEAPON",
        "SECURITY_THREAT",
        "THREAT_ACTOR",
        "MILITARY_UNIT",
        "INFRASTRUCTURE",
        "IP_ADDRESS",
        "HASH",
        "IOC",
        "CVE",
        "CWE",
        "MALWARE",
        "RANSOMWARE",
    ],
    "legal": [
        "PERSON",
        "ORGANIZATION",
        "AGREEMENT",
        "DATE",
        "LOCATION",
        "MONEY",
    ],
    "hr": [
        "PERSON",
        "DESIGNATION",
        "DEPARTMENT",
        "ORGANIZATION",
        "SKILL",
        "EMAIL",
        "PHONE",
        "DATE",
    ],
}

ENTITY_PRIORITY = {
    "PERSON": 100,
    "DOCTOR": 99,
    "ORGANIZATION": 98,
    "HOSPITAL": 97,
    "LOCATION": 96,
    "ADDRESS": 95,
    "CITY": 94,
    "STATE": 93,
    "COUNTRY": 92,
    "DATE": 91,
    "TIME": 90,
    "EMAIL": 89,
    "PHONE": 88,
    "WEBSITE": 87,
    "CREDIT_CARD": 86,
    "US_SSN": 86,
    "IBAN": 86,
    "PRODUCT": 85,
    "PROJECT": 84,
    "TECHNOLOGY": 83,
    "PROGRAMMING_LANGUAGE": 82,
    "MODEL_NAME": 81,
    "SKILL": 80,
    "DESIGNATION": 79,
    "DEPARTMENT": 78,
    "QUANTITY": 77,
    "TEAM": 76,
    "COMPETITION": 75,
    "GAME_NAME": 74,
    "MOVIE": 73,
    "BOOK": 72,
    "TV_SERIES": 71,
    "AUTHOR": 70,
    "ACTOR": 69,
    "MEDICINE": 68,
    "DISEASE": 67,
    "SYMPTOM": 66,
    "MEDICAL_PROCEDURE": 65,
    "BANK": 64,
    "BANK_ACCOUNT": 63,
    "IFSC": 62,
    "PAN": 61,
    "AADHAR": 60,
    "PASSPORT": 59,
    "GST": 58,
    "IP_ADDRESS": 57,
    "IP_ADDRESS_V6": 56,
    "MAC_ADDRESS": 55,
    "HASH": 54,
    "CVE": 53,
    "CWE": 52,
    "WEAPON": 51,
    "THREAT_ACTOR": 50,
    "MILITARY_UNIT": 49,
    "INFRASTRUCTURE": 48,
    "EVENT": 47,
    "AGREEMENT": 46,
    "AWARD": 45,
    "NATIONALITY": 44,
}

LABEL_MINIMUM_SCORES = {
    "PERSON": 0.52,
    "ORGANIZATION": 0.55,
    "LOCATION": 0.58,
    "CITY": 0.70,
    "STATE": 0.72,
    "COUNTRY": 0.72,
    "ADDRESS": 0.70,
    "EMAIL": 0.99,
    "PHONE": 0.99,
    "WEBSITE": 0.98,
    "DATE": 0.62,
    "TIME": 0.75,
    "QUANTITY": 0.70,
    "DESIGNATION": 0.62,
    "DEPARTMENT": 0.72,
    "PRODUCT": 0.62,
    "PROJECT": 0.68,
    "SKILL": 0.62,
    "NATIONALITY": 0.72,
    "TECHNOLOGY": 0.62,
    "PROGRAMMING_LANGUAGE": 0.75,
    "MODEL_NAME": 0.78,
    "TEAM": 0.78,
    "COMPETITION": 0.80,
    "GAME_NAME": 0.80,
    "MOVIE": 0.80,
    "BOOK": 0.80,
    "TV_SERIES": 0.82,
    "AUTHOR": 0.78,
    "ACTOR": 0.78,
    "DOCTOR": 0.78,
    "HOSPITAL": 0.80,
    "MEDICINE": 0.82,
    "DISEASE": 0.82,
    "SYMPTOM": 0.88,
    "MEDICAL_PROCEDURE": 0.88,
    "BANK": 0.80,
    "BANK_ACCOUNT": 0.98,
    "IFSC": 0.99,
    "PAN": 0.99,
    "AADHAR": 0.99,
    "PASSPORT": 0.99,
    "GST": 0.99,
    "CREDIT_CARD": 0.99,
    "US_SSN": 0.99,
    "IBAN": 0.99,
    "SWIFT_CODE": 0.99,
    "IP_ADDRESS": 0.99,
    "IP_ADDRESS_V6": 0.99,
    "MAC_ADDRESS": 0.99,
    "HASH": 0.99,
    "CVE": 0.99,
    "CWE": 0.99,
    "IOC": 0.97,
    "MALWARE": 0.88,
    "RANSOMWARE": 0.88,
    "WEAPON": 0.82,
    "SECURITY_THREAT": 0.90,
    "THREAT_ACTOR": 0.82,
    "MILITARY_UNIT": 0.82,
    "INFRASTRUCTURE": 0.78,
    "EVENT": 0.68,
    "AGREEMENT": 0.72,
    "AWARD": 0.78,
}

PROFILE_PRIORITY = {
    "medical": 100,
    "security": 95,
    "finance": 90,
    "legal": 88,
    "hr": 86,
    "technology": 85,
    "business": 80,
    "sports": 75,
    "media": 70,
    "general": 50,
}

# Per GLiNER call. Remaining labels are run in additional passes.
MAX_GLINER_LABELS = 12

ALL_LABELS = sorted(
    set(MODEL_LABEL_PROMPTS.keys())
    | STRUCTURED_LABELS
    | REGEX_ONLY_LABELS
    | DICTIONARY_ONLY_LABELS
)


def normalize_label(label: str | None) -> str:
    if not label:
        return "UNKNOWN"
    cleaned = str(label).strip().upper().replace("-", "_").replace(" ", "_")
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    return LABEL_ALIASES.get(cleaned, cleaned)
